// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vitkdwsasubrflxvhbxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpdGtkd3Nhc3VicmZseHZoYnh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMDkzODcsImV4cCI6MjA3MTY4NTM4N30.chG4YdaFU3iaEmaBYQrG8EGZjWswfglIqboMMjBXQ6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});